Repository CA-G12/Quiz-App-Team-14, pull requests merged in 2022-07, with the labels that each got.

#2 1 create file structure
  css/index.css
  css/quiz.css
  css/scoreboard.css
  html/quiz.html
  html/scorboard.html
  index.html
  js/index.js
  js/quiz.js
  js/scoreboard.js
Labels: approved

#8 4 create the home page
  css/index.css
  images/background.png
  images/galaxylogo.png
  index.html
Labels: approved

#10 created quiz.html and quiz.css files
  css/quiz.css
  download.png
  html/quiz.html
  js/quiz.js
  questions.json
Labels: approved

#11 6 create scoreboard page
  css/scoreboard.css
  html/scorboard.html
Labels: done

#15 13 nickname functionality
  css/index.css
  index.html
  js/index.js
  questions.json
Labels: awaiting-review

#16 Changes on quiz.js
  html/quiz.html
  js/quiz.js
Labels: approved

#17 14 create scoreboard functionality
  css/scoreboard.css
  html/scorboard.html
  js/scoreboard.js
Labels: approved

#23 Finished the project
  html/quiz.html
  js/quiz.js
Labels: approved

#29 changed the link to scoreboard in js file
  js/index.js
Labels: Minor Changes

#27 Fixing issues
  css/quiz.css
  html/quiz.html
  js/quiz.js
  questions.json
Labels: awaiting-review

#33 add new images to JSON file and changed the logo in images file
  images/galaxylogo.png
  questions.json
Labels: Minor Changes

#37 Fix check answer
  css/scoreboard.css
  download.png
  index.html
  js/index.js
  js/quiz.js
Labels: awaiting-review

#40 image change in json
  questions.json
Labels: done, approved, Minor Changes

#38 added media queries
  css/index.css
Labels: approved

#42 Made quiz.html responsive, changed some styles, also changed in quiz…
  css/quiz.css
  html/quiz.html
  js/index.js
  js/quiz.js
Labels: awaiting-review

#45 added animations and made the necessary changes in HTML, CSS, and JS …
  css/index.css
  css/quiz.css
  html/quiz.html
  js/quiz.js
Labels: awaiting-review

#47 43 add media queries for scorboard
  css/scoreboard.css
Labels: awaiting-review

#49 46 adding music to the project
  audio/music.m4a
  html/quiz.html
  js/quiz.js
Labels: awaiting-review

#51 50 shuffle question
  css/index.css
  css/quiz.css
  html/quiz.html
  js/quiz.js
Labels: awaiting-review

#54 cursor change
  css/quiz.css
Labels: Minor Changes

#55 48 create popup message
  css/scoreboard.css
  html/scorboard.html
  js/scoreboard.js
Labels: awaiting-review

#59 added sound effects
  audio/cheering.m4a
  audio/fail.m4a
  html/scorboard.html
  js/scoreboard.js
Labels: approved

#60 58 modify scoreboard style
  css/scoreboard.css
  js/scoreboard.js
Labels: approved

#63 62 modify scoreboard style
  css/scoreboard.css
  html/scorboard.html
Labels: awaiting-review

#64 more animations
  css/scoreboard.css
  html/scorboard.html
  js/scoreboard.js
Labels: approved

#66 65 minor changes quiz
  html/quiz.html
  html/scorboard.html
  js/quiz.js
Labels: approved

#68 added more details in the readme file
  README.md
Labels: awaiting-review

#69 Update README.md
  README.md
Labels: Minor Changes
